### ISSUE TITLE
node-[fs-extra] - fix max-call-stack v8.1.0

### ISSUE THREAD

**Issue by EvertonMelo** [centrifuge/centrifuge-ethereum-contracts#154]
# Dos system call node-fs

your version of node-fs-extra is not expected against the maximum system call.
fix max call stack size exceeded.

you need to correct the requirements for the version indicated otherwise you will be vulnerable to this type of attack.

## fixed on v8.x> 

https://github.com/jprichardson/node-fs-extra/commit/7c251d6df9cc24cae4c64b207acbed109eff697a

### more details for version

https://github.com/jprichardson/node-fs-extra/releases/tag/8.1.0

## focus the vulnerability: 
```
"devDependencies": {
    "ethereumjs-util": "6.1.0",
    "ethereumjs-wallet": "0.6.3",
    "fs-extra": "7.0.1", # that line
    "ganache-cli": "6.4.4",
    "husky": "2.4.1",
    "semver": "6.0.0",
    "solium": "1.2.4",
    "truffle": "5.0.22",
    "truffle-hdwallet-provider": "1.0.10",
    "yargs": "13.2.2",
    "zos": "2.4.0",
    "zos-lib": "2.4.0"
  }
}
```
font: https://github.com/centrifuge/centrifuge-ethereum-contracts/blob/develop/package.json#L40

**Comment by pstehlik** [comment]
Thanks for the ticket. We are aware of this one and didn't fix it yet as high priority as the issue doesn't impact our smart contract security.
