### ISSUE TITLE
yargs update 13.3.0 critical fix 

### ISSUE THREAD

**Issue by EvertonMelo** [centrifuge/centrifuge-ethereum-contracts#155]
# various bugs and security fixes

1) [yargs-parser update addressing several parsing bugs](https://github.com/yargs/yargs/pull/1357/files)

2) [do not allow additional positionals in strict](https://github.com/yargs/yargs/commit/35d777c8db9548763a8f00c95bbd56a9c0f31084)

3) [properties accessed on singleton now reflect current state of in](https://github.com/yargs/yargs/commit/409d35bfb10928b34b2a6b29492878d42c4825df)

In order not to suffer from the above problems, update to version is required.

### more details for version

https://github.com/yargs/yargs/releases/tag/v13.3.0 

## focus the vulnerability: 
```
"devDependencies": {
....
     "yargs": "13.2.2", # that line
    "zos": "2.4.0",
    "zos-lib": "2.4.0"
  }
}
```
font: https://github.com/centrifuge/centrifuge-ethereum-contracts/blob/develop/package.json#L47

**Comment by pstehlik** [comment]
Thanks for the ticket. We are aware of this one and didn't fix it yet as high priority as the issue doesn't impact our smart contract security.
