### ISSUE TITLE
create generic centchain validated NFT 

### ISSUE THREAD

**Issue by mikiquantum** [centrifuge/centrifuge-ethereum-contracts#159]
mint function:
- [input] tokenID
- [input] arbitrary number of values(bytes) as metadata
- [input ]bundleHash
- will look at bridge asset contract registry for the bundled hash and check if from address of request matches allowed dids in asset
- mint token base call

**Comment by vedhavyas** [comment]
Fixed as part of this PR: https://github.com/centrifuge/privacy-enabled-erc721/pull/20
