### ISSUE TITLE
Bridge Anchor Repository

### ISSUE THREAD

**Issue by mikiquantum** [centrifuge/centrifuge-ethereum-contracts#160]
- Assume operators module exists
- import operator interface
- constructor will take operator smart contract addresses
- public function to store anchor request with operator signature + validation
- logic to trigger bridge anchor state change when minimum number of operator signatures received.
   - when last signature received then confirm anchor + event
- public getAnchorByID function conforming with legacy anchorRepo

**Comment by vedhavyas** [comment]
This is not valid anymore. Hence, closing

cc: @lucasvo @mikiquantum
