### ISSUE TITLE
The mint method should validate the signature

### ISSUE THREAD

**Issue by rdinicut** [centrifuge/centrifuge-ethereum-contracts#61]
The mint method should check the CentId provided in the collaborator proofs has a valid identity and the signature provided is generated with the corresponding identity key

We need to:
- Define the singing schema. This is coupled to the ETH_MESSAGE_KEY and how we handle MACs in our smart contracts
- convert the collaborator value to uint48. The proof is generated with the string value the centrifuge id is uint48.  We can work around this if you use strings for the centId
- Retrieve the Identity and check signature

**Comment by lucasvo** [comment]
Closing this issue as it will be implemented differently with new identities
