### ISSUE TITLE
Add "customer" account/signature to PayOb NFT proofs 

### ISSUE THREAD

**Issue by pstehlik** [centrifuge/centrifuge-ethereum-contracts#86]
To support reverse factoring use cases - or at the very least allowing factoring use cases to take into account a buyer-side receipt, the proof of a buyer's signature should be included (optionally) in the minting process.

## Open Questions
* Is it possible to verify the document signature on-chain? Meaning to check if the buyer signed the document at its current state?
* How to best have "optional" parameters in an NFT?
  * An alternative solution would be to create a separate registry that has this field as a required parameter.

**Comment by lucasvo** [comment]
We need to use the identity's proxy method to call the NFT registry when implementing this. This might be some extra work.
